### ISSUE TITLE
Update PHI-Deidentifier-Example to New Schema

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/phi-deidentifier-example#155]

**Comment by cascadianblue** [comment]
@tschaffter I think we said to do this, but the [schema version](https://github.com/nlpsandbox/phi-deidentifier-example/blob/6f12fb1f7cd9dac427912f95a396062641fe371e/server/openapi_server/controllers/tool_controller.py#L26) of the PHI-Deidentifier-Example seems to match the latest schema version, [1.2.0](https://github.com/nlpsandbox/nlpsandbox-schemas). So this ticket should be closed, right?

**Comment by tschaffter** [comment]
Looks like it. Was the comment about the app (react)?

**Comment by cascadianblue** [comment]
@tschaffter good question. I checked and it looks like the React app is also using the current schema version: https://github.com/nlpsandbox/phi-deidentifier-app/commit/84bb47e2085665bb8e2b8f10130a863cead22bca
